name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: test/test_test
          ref: refs/heads/master
          path: test
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test 